### PR TITLE
Rename the check scripts to allow for parallelization by new versions of "build"

### PR DESCRIPTION
**Pull request by peti**
Move all scripts that can run in parallel to the same run-level (50).

This change is safe to apply even for current versions of "build". Versions
that contain https://github.com/openSUSE/obs-build/pull/359, however, will take
advantage of this change to parallelize the post-build-checks phase.

Currently, the only two scripts that cannot run in parallel are:

 - 00-check-install-rpms (needs to run first) and

 - 99-check-remove-rpms (needs to run last).

Everything else has been moved to run-level 50.

### CODE REVIEW

**Comment by lnussel** [comment]
why not run scripts with the same prefix number in parallel like the old sysv startpar did?

**Comment by peti** [comment]
Updated to implement the behavior suggested in https://github.com/openSUSE/post-build-checks/pull/10#issuecomment-305121759.

**Comment by peti** [comment]
Ping?

**Comment by scarabeusiv** [comment]
Looks fine, all comments addressed so lets try this

**Pull request merged**
