### PR TITLE
03-check-binary-kernel-log: Fix quoting, skip for kernel-docs

### PR DESCRIPTION
**Pull request by StefanBruens**

### CODE REVIEW

**Comment by StefanBruens** [comment]
Can anyone review/pull this?

**Comment by scarabeusiv** [comment]
@msmeissn, @lnussel : guys? It looks good :)

**Comment by coolo** [comment]
lnussel will be back from vacation next week

**Comment by msmeissn** [comment]
Both changes look good to me.

**Comment by msmeissn** [comment]
(i dont have merge rights, but from my point of view its good to merge)

**Pull request merged**
